Web/04_django/Ex/WUNDERLIST/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('password/', views.change_password, name='change_password'),
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

Web/04_django/Ex/WUNDERLIST/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    # path('edit/<int:pk>/', views.edit, name='edit'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

Web/04_django/Ex/WUNDERLIST/todos/models.py
from django.db import models
from django.conf import settings

class Todo(models.Model):
    title = models.CharField(max_length=30)
    due_date = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

Web/04_django/Ex/WUNDERLIST/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model

class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)

Web/04_django/Ex/WUNDERLIST/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from .forms import UserCustomChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash

def signup(request):
    if request.user.is_authenticated:
        return redirect('todos:index')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('todos:index')
    else:
        form = UserCreationForm()
        return render(request, 'accounts/auth_form.html', {'form':form})

def login(request):
    if request.user.is_authenticated:
        return redirect('todos:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('todos:index')
    else:
        form = AuthenticationForm(request)
        return render(request, 'accounts/auth_form.html', {'form':form})
            
def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        return redirect('todos:index')
    return redirect('todos:index')

def edit(request):
    if request.method == 'POST':
        form = UserCustomChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('todos:index')
    else:
        form = UserCustomChangeForm(instance=request.user)
        return render(request, 'accounts/auth_form.html', {'form':form})

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('todos:index')
    else:
        form = PasswordChangeForm(request.user)
        return render(request, 'accounts/auth_form.html', {'form':form})

def delete(request):
    if request.method == 'POST':
        request.user.delete()
    return redirect('todos:index')

Web/04_django/Ex/WUNDERLIST/todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Todo
import requests
from decouple import config

def index(request):
    todos = Todo.objects.all()[::-1]
    context = {
        'todos':todos
    }
    return render(request, 'todos/index.html', context)

# def new(request):
#     return render(request, 'todos/new.html')

@login_required
def create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')
        user = request.user

        Todo.objects.create(title=title, due_date=due_date, user=user)

        base = 'https://api.telegram.org'
        token = config('TOKEN')
        url = f'{base}/{token}/getUpdates'

        res = requests.get(url)
        data = res.json()

        chat_id = data['result'][0]['message']['chat']['id']
        text = f'일정: {title} / 날짜: {due_date}'

        url = f'{base}/{token}/sendMessage?chat_id={chat_id}&text={text}'
        requests.get(url)
        return redirect('todos:index')
    else:
        return render(request, 'todos/new.html')

# def edit(request, pk):
#     todo = Todo.objects.get(id=pk)
#     context = {
#         'todo':todo
#     }
#     return render(request, 'todos/edit.html', context)

@login_required
def update(request, pk):
    # todo = Todo.objects.get(id=pk)
    todo = get_object_or_404(Todo, id=pk)
    if request.method == 'POST':
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')
        user = request.user
        
        todo.title = title
        todo.due_date = due_date
        todo.user = user
        todo.save()
        return redirect('todos:index')
    else:
        todo = Todo.objects.get(id=pk)
        context = {
            'todo':todo
        }
        return render(request, 'todos/edit.html', context)

def delete(request, pk):
    # todo = Todo.objects.get(id=pk)
    todo = get_object_or_404(Todo, id=pk)
    todo.delete()
    return redirect('todos:index')

Web/04_django/Ex/WUNDERLIST/todos/templates/todos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width={device-width}, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Wunderlist</title>
</head>
<body>
    <div class='container'>
        {% if user.is_authenticated %}
        <h1>Hello, {{ user.username }}!</h1>
        <a href="{% url 'accounts:edit' %}">회원정보 수정</a>
        <a href="{% url 'accounts:change_password' %}">비밀번호 변경</a>
        <form action="{% url 'accounts:logout' %}" method='POST' style='display: inline;'>
            {% csrf_token %}
            <button type='submit' class='btn btn-secondary'>로그아웃</button>
        </form>
        <form action="{% url 'accounts:delete' %}" method='POST' style='display: inline;'>
            {% csrf_token %}
            <button type='submit' class='btn btn-secondary'>회원탈퇴</button>
        </form>
        <a href="{% url 'todos:create' %}">글 작성하기</a>
        {% else %}
        <h1>Hello, Stranger~</h1>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'todos:create' %}">글을 쓰려면 로그인이 필요합니다</a>
        {% endif %}
        <a href="{% url 'todos:index' %}">글 모아보기</a>
    </div>
    {% block body %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

Web/04_django/Ex/WUNDERLIST/todos/templates/todos/edit.html
{% extends 'todos/base.html' %}

{% block body %}
<h1 class='text-center'> EDIT </h1>
<form action="{% url 'todos:update' todo.id %}" method="POST" class='container'>
    {% csrf_token %}
    <input type="text" name="title" value="{{ todo.title }}">
    <input type="date" name="due-date" value="{{ todo.due_date | date:'Y-m-d'}}">
    <input type="submit">
</form>
{% endblock %}

Web/04_django/Ex/WUNDERLIST/todos/templates/todos/index.html
{% extends 'todos/base.html' %}

{% block body %}
<h1 class='text-center'> INDEX </h1>
<div class='container'>
    {% for todo in todos %}
        <li>{{ todo.due_date }} : {{ todo.title }} | 
            {% if request.user == todo.user %}<a href="{% url 'todos:update' todo.id %}">수정</a> | <a href="{% url 'todos:delete' todo.id %}">삭제</a>{% endif %}</li>    
    {% endfor %}
</div>
{% endblock %}

Web/04_django/Ex/WUNDERLIST/todos/templates/todos/new.html
{% extends 'todos/base.html' %}

{% block body %}
<h1 class="text-center"> NEW </h1>
<form action="{% url 'todos:create' %}" method="POST" class="container">
    {% csrf_token %}
    <input type="text" name="title">
    <input type="date" name="due-date">
    <input type="submit">
</form>
{% endblock %}