Web/04_django/LECTURE_CODE/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<username>/profile/', views.profile, name='profile'),
    path('<int:user_pk>/password/', views.change_password, name='change_password'),
    path('<int:user_pk>/edit/', views.edit, name='edit'),
    path('<int:user_pk>/delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('', views.index, name='index'),
]

Web/04_django/LECTURE_CODE/boards/urls.py
from django.urls import path
from boards import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new),
    path('create/', views.create, name='create'),
    path('<int:article_id>/', views.detail, name='detail'),
    # path('<int:article_id>/edit/', views.edit),
    path('<int:article_id>/update/', views.update, name='update'),
    path('<int:article_id>/delete/', views.delete, name='delete'),
    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_id>/like/', views.like, name='like'),
    path('<int:article_id>/follow/<int:user_id>/', views.follow, name='follow'),
]

Web/04_django/LECTURE_CODE/juan_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 다른 방식
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# /media/ 들어오는 요청들을 통과시켜주세요.
# static()

Web/04_django/LECTURE_CODE/boards/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill, Thumbnail, ResizeToFit

def articles_image_path(instance, filename):
    return f'articles/user.{instance.user.pk}/images/{filename}'

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # image = models.ImageField(blank=True)         # 기본 이미지 업로드
    image = ProcessedImageField(
        upload_to = articles_image_path,            # 저장 위치
        # upload_to = '',                           # 저장 위치(/media/)
        processors = [ResizeToFit(width=200, upscale=False)],
        # processors = [ResizeToFill(300, 200)],    # 처리할 작업 목록[이미지 사이즈 조정(가로300px, 세로200px)]
        # processors = [Thumbnail(100, 100)],       # 처리할 작업 목록[Thumbnail 사이즈(가로100px, 세로100px)]
        format = 'png',                             # 저장 포멧
        options = {'quality':90},                   # 옵션(이미지 품질 수치)
        blank = True,                               # 빈 값 허용
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)

    # article = Article.objects.get(id=1)
    # user -> admin

    #1. 1:N
    # article.user # 게시글을 쓴 유저(admin)
    # user.article_set.all() # 유저(admin)가 쓴 게시글 전체 (겹침)

    #2. M:N
    # article.like_users # 1번 게시글을 좋아요 한 유저
    # user.article_set.all() # 유저가 좋아요 한 게시글 전체 (겹침)
    # --> user.like_articles.all() # 유저(admin)이 좋아요를 누른 모든 게시글들

    def __str__(self):
        return f'{self.id}: {self.title}'

class Comment(models.Model):
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)    # 1 대 N 의 관계
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

Web/04_django/LECTURE_CODE/boards/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label="제목",
        widget=forms.TextInput(attrs={
            'placeholder': 'Enter a Title'
        })
    )
    content = forms.CharField(
        label="내용",
        widget=forms.Textarea(attrs={
            'class': 'input-content',
            'rows':5,
            'cols':50,
            'placeholder':'Enter the content',
        })
    )
    # image = forms.ImageField(
    #     label="이미지",
    #     widget=forms.FileInput()
    # )

    class Meta:
        model = Article
        fields = ['title','content', 'image',]

# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         label="제목",
#         widget=forms.TextInput(attrs={
#             'placeholder': 'Insert Title'
#         })
#     )
#     content = forms.CharField(
#         label="내용",
#         widget=forms.Textarea(attrs={
#             'class': 'input-content',
#             'rows':5,
#             'cols':50,
#             'placeholder':'Fill in this Box',
#         })
#     )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

Web/04_django/LECTURE_CODE/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_POST

def index(request):
    articles = Article.objects.order_by('-pk')
    context = {'articles':articles}
    return render(request, 'boards/index.html', context)

# def new(request):
#     return render(request, 'new.html')

@login_required
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES) # image 업로드를 위해 request.FILES 추가, update 함수에도.
        if form.is_valid():
            article = form.save(commit=False)
            # article.image = request.FILES.get('image')
            article.user = request.user
            article.save()
            # title = form.cleaned_data.get('title')
            # content = form.cleaned_data.get('content')
            # article = Article.objects.create(title=title, content=content)
            return redirect('articles:detail', article.id)
    else:
        form = ArticleForm()
        return render(request, 'boards/form.html', {'form':form})

# def create(request):
#     if request.method == "POST":
#         article = Article()
#         article.title = request.POST.get('title')
#         article.content = request.POST.get('content')
#         article.image = request.FILES.get('image')
#         article.save()
#         return redirect('articles:index')
#     else:
#         return render(request, 'create.html')
    
    # 2nd method
    # title = request.GET.get('title')
    # content = request.GET.get('content')
    # article = Article(title=title, content=content)
    # article.save()

    # 3rd method
    # Article.objects.create(title=title, content=content)

def detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    person = get_object_or_404(get_user_model(), id=article.user.id)
    # article = Article.objects.get(id=article_id)
    comments = article.comment_set.order_by('-pk')
    comment_form = CommentForm()
    context = {
        'article':article,
        'comments':comments,
        'comment_form':comment_form,
        'person':person,
    }
    return render(request, 'boards/detail.html', context)

# def edit(request, article_id):
#     article = Article.objects.get(id=article_id)
#     return render(request, 'edit.html', {
#         'article':article,
#     })

@login_required
def update(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if article.user == request.user:
    # article = Article.objects.get(id=article_id)
        if request.method == "POST":
            form = ArticleForm(request.POST, request.FILES, instance=article)   # request.FILES 추가
            if form.is_valid():
                article = form.save(commit=False)
                # article.image = request.FILES.get('image')
                article.user = request.user
                article.save()
                # article.title = form.cleaned_data.get('title')
                # article.content = form.cleaned_data.get('content')
                # article.save()
                return redirect('articles:detail', article.id)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
        # form = ArticleForm(initial=article.__dict__)
    return render(request, 'boards/form.html', {'form':form,'article':article})

# def update(request, article_id):
#     article = Article.objects.get(id=article_id)
#     if request.method == "POST":
#         article.title = request.POST.get('title')
#         article.content = request.POST.get('content')
#         article.image = request.FILES.get('image')
#         article.save()
#         return redirect('articles:detail', article.id)
#     else:
#         context = {
#             'article':article,
#         }
#         return render(request, 'update.html', context)

@require_POST   # POST 요청이 아닌 요청이 들어오면 405에러를 보여준다
def delete(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if article.user == request.user:
        if request.method == "POST":
            # article = Article.objects.get(id=article_id)
            article.delete()
            return redirect('articles:index')
        # else:
        #     return redirect('articles:detail', article.id)
    else:
        return redirect('articles:index')

@login_required
@require_POST   # POST 요청이 아닌 요청이 들어오면 405에러를 보여준다
def comment_create(request, article_id):
    # Comment.objects.create(
    #     content = request.GET.get('content'),
    #     article = Article.objects.get(id=article_id)
    # )
    # return redirect('articles:detail', article_id)
    article = Article.objects.get(id=article_id)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
    # comment = Comment()
    # comment.content = request.POST.get('content')
    # comment.article = Article.objects.get(id=article_id)
    # comment.user = request.user
    # comment.save()
    return redirect('articles:detail', article.id)

@login_required
# @require_POST     # request.user가 comment.user인 경우에만 삭제 버튼이 보이게 하고 이 버튼은 GET요청으로 보내도록 함(댓글과 삭제버튼 a태그로 한줄표시하려고)
def comment_delete(request, article_id, comment_id):
    article = Article.objects.get(id=article_id)
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return redirect('articles:detail', article.id)

@login_required
def like(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    user = request.user
    if article.like_users.filter(id=user.id).exists(): # 좋아요를 누른 사람이 이미 좋아요 한 경우
        article.like_users.remove(user) # 좋아요 취소
    else:
        article.like_users.add(user)
    return redirect('articles:index')

# 팔로우 : 특정 대상을 팔로우하는 경우 그 대상의 소식을 만날 수 있습니다.
# 팔로워 : 나 또는 특정 대상을 팔로우하는 사람
# 팔로잉 : 나 또는 특정 대상이 팔로우하는 사람
@login_required
def follow(request, article_id, user_id):
    person = get_object_or_404(get_user_model(), id=user_id)
    if request.user in person.followers.all():
        person.followers.remove(request.user)
    else:
        person.followers.add(request.user)
    return redirect('articles:detail', article_id)

Web/04_django/LECTURE_CODE/boards/templates/boards/_article.html
<!-- index.html 에 아래 내용을 써도 좋지만 너무 길어지면 가독성이 떨어지기 때문에 모듈화 한다. -->
<div class='card-body'>
    <a href="{% url 'articles:like' article.id %}" class='card-link'>
        {% if user in article.like_users.all %}
            <!-- <button class="btn btn-danger">LIKE</button> -->
            <i class='fas fa-heart fa-lg' style='color:crimson'></i>
        {% else %}
            <!-- <button class='border border-danger text-danger rounded-lg'>LIKE?</button> -->
            <i class='far fa-heart fa-lg' style='color:black'></i>
        {% endif %}
    </a>
    <p class='card-text' style='display:inline'><b>- {{ article.like_users.count }} 명이 좋아합니다.</b></p>
</div>

Web/04_django/LECTURE_CODE/boards/templates/boards/_nav.html
<div class="container">
    {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'articles:index' %}">Welcome {{ request.user.username }}!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <form action="{% url 'accounts:profile' user.username %}" method="POST" style='display:inline'>
                {% csrf_token %}
                <input class="nav-item nav-link border-0 bg-transparent" type="submit" value="/ Profile">
            </form>
            <a class="nav-item nav-link" href="{% url 'accounts:edit' user.pk %}">/ Edit Account <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'accounts:change_password' user.pk %}">/ Change Password</a>
            <form action="{% url 'accounts:logout' %}" method="POST" style='display:inline'>
                {% csrf_token %}
                <input class="nav-item nav-link border-0 bg-transparent" type="submit" value="/ Logout">
            </form>
            <form action="{% url 'accounts:delete' user.pk %}" method='POST' style='display:inline'>
                {% csrf_token %}
                <input class="nav-item nav-link border-0 bg-transparent" type="submit" value="/ Quit">
            </form>
            <a class="nav-item nav-link" href="{% url 'accounts:index' %}">/ Users</a>
          </div>
        </div>
    </nav>
    <!-- <h1 style='display:inline'>Hello, {{ user.username }}</h1>
    /<a class="btn btn-light btn-lg" href="{% url 'accounts:edit' user.pk %}" role="button">Edit Account</a>
    /<a class="btn btn-light btn-lg" href="{% url 'accounts:change_password' user.pk %}" role="button">Change Password</a>
    /<form action="{% url 'accounts:logout' %}" method="POST" style='display:inline'>
        {% csrf_token %}
        <input class="btn btn-light btn-lg" type="submit" value="logout">
    </form>
    /<form action="{% url 'accounts:delete' user.pk %}" method='POST' style='display:inline'>
        {% csrf_token %}
        <input class="btn btn-dark btn-lg" type="submit" value="Quit">
    </form> -->
    {% else %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'articles:index' %}">Welcome Juan's Blog!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">/ LogIn <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">/ SignUp</a>
          </div>
        </div>
    </nav>
        <!-- <h1>
            <a class="btn btn-dark btn-lg" href="{% url 'accounts:login' %}" role="button">LogIn</a>
            <a class="btn btn-dark btn-lg" href="{% url 'accounts:signup' %}" rolr="button">SignUp</a>
        </h1> -->
    {% endif %}
    <hr>
</div>

Web/04_django/LECTURE_CODE/boards/templates/boards/_profile.html
<div class="jumbotron text-center text-white bg-dark">
    <p class="lead mb-1">작성자 정보</p>
    <h2 class="display">{{ article.user }}</h2>
    <hr class="border-white">
    <p class="lead">
        팔로잉 : {{ person.followings.all | length }}
        팔로워 : {{ person.followers.all | length }}
    </p>
    {% if user != person %}
        {% if user in person.followers.all %}
    <!-- '웹 접근성' :  a 태그의 'role'속성은 시각장애인들을 위해 스크린리더가 읽어주는 속성이다. img의 alt 속성과 비슷? -->
            <a class='btn btn-primary' href="{% url 'articles:follow' article.id person.id %}" role="button">Unfollow</a>
        {% else %}
            <a class='btn btn-primary' href="{% url 'articles:follow' article.id person.id %}" role="button">Follow</a>
        {% endif %}
    {% endif %}
</div>

Web/04_django/LECTURE_CODE/boards/templates/boards/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/eb4e6c57f5.js" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <title></title>
</head>
<body>
    {% include 'boards/_nav.html' %}
    {% block body %}
    {% endblock %}
    <div class="container">
        <div class="sticky-bottom">
            <p class="lead text-right mr-4 mb-3">Copyright 2019. Juan. All rights reserved.</p>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

Web/04_django/LECTURE_CODE/boards/templates/boards/detail.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}
{% block title %}DETAIL{% endblock %}
{% block body %}
<div class="container">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">DETAIL</h1>
            <p class="lead">This is Article</p>
        </div>
    </div>
</div>
<!-- <h1 align=center>DETAIL</h1> -->
<div class="container">
    <h3>No.{{ article.id}}: {{ article.title }}</h3>
    <p>내용: {{ article.content }}</p>
    {% if article.image %}
        <img src="{{ article.image.url }}" alt="{{ article.image }}">
    {% else %}
        <img src="/media/noimages.jpg" alt="no_image">
    {% endif %}
    <p>작성시간: {{ article.created_at }}</p>
    <p>수정시간: {{ article.updated_at }}</p>
    <hr>
    <h4>Comment {% if comments %}/ {{ comments | length }}개의 댓글{% endif %}</h4>
    {% if user.is_authenticated %}
    <form action="{% url 'articles:comment_create' article.id %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form comment_form layout='horizontal' %}
        {% bootstrap_button "입력" button_class='btn btn-dark' %}
        <!-- {{ comment_form }} -->
        <!-- Comment: <input type="text" name="content"> -->
        <!-- <input type="submit" value="입력" class="btn btn-dark"> -->
    </form>
    {% else %}
    <div class='text-center'>
        <a href="{% url 'accounts:login' %}"><button class="btn btn-warning">댓글을 쓰려면 로그인 해주세요</button></a>
    </div>
    {% endif %}
    {% if comments %}
        <br>
        {% for comment in comments %}
            <ul><li>댓글 {{ forloop.revcounter }}: {{ comment.content }} {% if user == comment.user %} - <a href="{% url 'articles:comment_delete' article.id comment.id %}"><button class="btn btn-light">삭제</button></a>{% endif %}</li></ul>
        {% endfor %}
    {% else %}
        <br>
        No comment...ㅠㅠ
    {% endif %}
    <hr>
    {% include 'boards/_profile.html' %}
    <hr>
    <div class='mb-5'>
        <a href="{% url 'articles:index' %}"><button class="btn btn-info">목록</button></a>
        {% if user == article.user %}
        <a href="{% url 'articles:update' article.id %}"><button class="btn btn-info">수정</button></a>
        <form action="{% url 'articles:delete' article.id %}" method="POST" style='display:inline'>
            {% csrf_token %}
            <button class="btn btn-info">삭제</button>
        </form>
        {% endif %}
    </div>
    <!-- <a href="{% url 'articles:delete' article.id %}"><button class="btn btn-info">삭제</button></a> -->
</div>
{% endblock %}

Web/04_django/LECTURE_CODE/boards/templates/boards/form.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}

{% block body %}
<div class="container">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            {% if request.resolver_match.url_name == "create" %}
            <h1 class="display-4">CREATE</h1>
            <p class="lead">Create a New Article</p>
            {% else %}
            <h1 class="display-4">EDIT</h1>
            <p class="lead">Edit your Article</p>
            {% endif %}
        </div>
    </div>
</div>
<!-- <h1 align=center>CREATE</h1> -->
<div class="container">
    <form action="" method="POST" enctype="multipart/form-data" style='display:inline'>
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <!-- 이미지: <input type="file" name="image" accept="image/*"> <br> -->
        {% bootstrap_button "등록" button_type='submit' button_class='btn btn-primary' %}
        <!-- {{ form.as_p }} -->
        <!-- <div>
            <input type="submit" value="등록" class="btn btn-dark">
        </div> -->
    </form>
    {% if request.resolver_match.url_name == "create" %}
        <a href="{% url 'articles:index' %}" style='display:inline'><button class="btn btn-dark">목록으로</button></a>
    {% else %}
        <a href="{% url 'articles:detail' article.id %}" style='display:inline'><button class="btn btn-dark">수정취소</button></a>
    {% endif %}
</div>
{% endblock %}

Web/04_django/LECTURE_CODE/boards/templates/boards/index.html
{% extends 'boards/base.html' %}
{% block title %}INDEX{% endblock %}
{% block body %}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Juan's BLOG</h1>
        <p class="lead">HAPPY HACKING LIFE</p>
        <hr class="my-4">
        <p class='font-italic'>Whatever you want to say</p>
        {% if user.is_authenticated %}
        <a class="btn btn-primary btn-lg" href="{% url 'articles:create' %}" role="button">새 글</a>
        {% else %}
        <a class="btn btn-primary btn-lg" href="{% url 'accounts:login' %}" role="button">Log In</a>
        {% endif %}
    </div>
</div>
<!-- <h1 align=center>INDEX</h1> -->
<!-- <a href="{% url 'articles:create' %}"><button class="btn btn-dark">새 글</button></a> -->
<div class="container">
    {% for article in articles %}
    <div>
        <a href="{% url 'articles:detail' article.id %}" style='display:inline'>No. {{ article.id }}: {{ article.title }}</a>
        <!-- <p style='display:inline'> | <b>writer: {{ article.user }}</b></p><br> -->
        <form action="{% url 'accounts:profile' article.user %}" method="POST" style="display:inline">
            {% csrf_token %}
            | writer: <input type="submit" class="border-0 bg-transparent font-weight-bold" value="{{ article.user }}">
        </form><br>
        <p style='display:inline'>작성시간: {{ article.created_at }} | </p>
        {% if user == article.user %}
        <a href="{% url 'articles:update' article.id %}"><button class="btn btn-light">수정</button></a>
        <form action="{% url 'articles:delete' article.id %}" method="POST" style="display:inline">
            {% csrf_token %}
            <input type="submit" class="btn btn-light" value="삭제">
        </form>
        <!-- <a href="{% url 'articles:delete' article.id %}"><button class="btn btn-light">삭제</button></a></p> -->
        {% endif %}
        {% include 'boards/_article.html' %}
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock %}