Web/04_django/Open_API/DJANGO_MOVIE/django_movie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

Web/04_django/Open_API/DJANGO_MOVIE/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('<int:movie_pk>/scores/<int:score_pk>/delete/', views.score_delete, name='score_delete'),
    path('<int:movie_pk>/scores/new/', views.score_new, name='score_new'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('', views.index, name='index'),
]

Web/04_django/Open_API/DJANGO_MOVIE/movies/models.py
from django.db import models

class Genre(models.Model):
    name = models.CharField(max_length=20)

class Movie(models.Model):
    title = models.CharField(max_length=20)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=200)
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

class Score(models.Model):
    content = models.CharField(max_length=200)
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

Web/04_django/Open_API/DJANGO_MOVIE/movies/views.py
from django.shortcuts import render, redirect
from .models import Genre, Movie, Score

def index(request):
    movies = Movie.objects.all()
    return render(request, 'movies/index.html', {'movies':movies})

def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    scores = movie.score_set.order_by('-pk')
    return render(request, 'movies/detail.html', {'movie':movie, 'scores':scores})

def update(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        movie.title = request.POST.get('title')
        movie.audience = request.POST.get('audience')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        return render(request, 'movies/edit.html', {'movie':movie})

def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('movies:index')
    else:
        return redirect('movies:detail', movie.pk)

def score_new(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        score = Score()
        score.content = request.POST.get('content')
        score.score = request.POST.get('score')
        score.movie = movie
        score.save()
    return redirect('movies:detail', movie.pk)

def score_delete(request, movie_pk, score_pk):
    # movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        score = Score.objects.get(pk=score_pk)
        score.delete()
    return redirect('movies:detail', movie_pk)

Web/04_django/Open_API/DJANGO_MOVIE/movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>MOVIEs</title>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

Web/04_django/Open_API/DJANGO_MOVIE/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block body %}
<h1 class="text-center">Movie Detail</h1>
<hr>
<div class="container">
    <h2 class="text-center">{{ movie.title }}</h2>
    <hr>
    <p>관객수 : {{ movie.audience }}</p><br>
    <p>포스터 : <img src="{{ movie.poster_url }}" alt="poster" width='200px'></p>
    <p>소개 : {{ movie.description }}</p><br>
</div>
<a href="{% url 'movies:index' %}"><button class='btn btn-info' style="display:inline">목록</button></a>
<a href="{% url 'movies:update' movie.pk %}"><button class='btn btn-secondary' style="display:inline">수정</button></a>
<form action="{% url 'movies:delete' movie.pk %}" style="display:inline" method="POST">
    {% csrf_token %}
    <button class='btn btn-danger'>삭제</button>
</form>
<hr>
<form action="{% url 'movies:score_new' movie.pk %}" method="POST">
    {% csrf_token %}
    한줄 평: <input type="text" name="content">
    평점: <input type="number" min="0" max="10" name="score">
    <button class="btn btn-success">입력</button>
</form>
<hr>
<h3>한줄평 | 총 {{ scores|length }}개의 한줄평이 있습니다.</h3><br>
{% for score in scores %}
<ul>
    <li>한줄평: {{ score.content }} / 평점: {{ score.score }}
        <form action="{% url 'movies:score_delete' movie.pk score.pk %}" style="display:inline" method="POST">
            {% csrf_token %}
            <button class='btn btn-warning btn-sm'>삭제</button>
        </form>
    </li>
</ul>
{% empty %}
<p>한줄평이 아직 없습니다. 한줄평을 작성해 주세요.</p>
{% endfor %}
{% endblock %}

Web/04_django/Open_API/DJANGO_MOVIE/movies/templates/movies/edit.html
{% extends 'movies/base.html' %}
{% block body %}
<h1 class='text-center'>EDIT</h1>
<hr>
<form action="" method="POST" style="display:inline">
    {% csrf_token %}
    제목: <input type="text" name="title" value="{{ movie.title }}"><br>
    관객: <input type="number" name="audience" value="{{ movie.audience }}"><br>
    포스터: <input type="text" name="poster_url" value="{{ movie.poster_url }}"><br>
    소개: <textarea name="description" id="" cols="30" rows="10">{{ movie.description }}</textarea><br>
    <button class='btn btn-info'>수정</button>
</form>
<a href="{% url 'movies:index' %}"><button class='btn btn-secondary' style="display:inline">목록보기</button></a>
{% endblock %}

Web/04_django/Open_API/DJANGO_MOVIE/movies/templates/movies/index.html
{% extends 'movies/base.html' %}
{% block body %}
<h1 class='text-center'>Movie Index</h1>
<hr>
{% for movie in movies %}
<ul>
    <li><h3>No.{{ movie.id }} - <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a></h3></li>
    <img src="{{ movie.poster_url }}" alt="poster" width="200px">
</ul>
{% endfor %}
{% endblock %}