Web/04_django/LECTURE_CODE/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<username>/profile/', views.profile, name='profile'),
    path('<int:user_pk>/password/', views.change_password, name='change_password'),
    path('<int:user_pk>/edit/', views.edit, name='edit'),
    path('<int:user_pk>/delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('', views.index, name='index'),
]

Web/04_django/LECTURE_CODE/boards/urls.py
from django.urls import path
from boards import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new),
    path('create/', views.create, name='create'),
    path('<int:article_id>/', views.detail, name='detail'),
    # path('<int:article_id>/edit/', views.edit),
    path('<int:article_id>/update/', views.update, name='update'),
    path('<int:article_id>/delete/', views.delete, name='delete'),
    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_id>/like/', views.like, name='like'),
    path('<int:article_id>/follow/<int:user_id>/', views.follow, name='follow'),
]

Web/04_django/LECTURE_CODE/juan_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 다른 방식
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# /media/ 들어오는 요청들을 통과시켜주세요.
# static()

Web/04_django/LECTURE_CODE/boards/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill, Thumbnail, ResizeToFit

def articles_image_path(instance, filename):
    return f'articles/user.{instance.user.pk}/images/{filename}'

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # image = models.ImageField(blank=True)         # 기본 이미지 업로드
    image = ProcessedImageField(
        upload_to = articles_image_path,            # 저장 위치
        # upload_to = '',                           # 저장 위치(/media/)
        processors = [ResizeToFit(width=200, upscale=False)],
        # processors = [ResizeToFill(300, 200)],    # 처리할 작업 목록[이미지 사이즈 조정(가로300px, 세로200px)]
        # processors = [Thumbnail(100, 100)],       # 처리할 작업 목록[Thumbnail 사이즈(가로100px, 세로100px)]
        format = 'png',                             # 저장 포멧
        options = {'quality':90},                   # 옵션(이미지 품질 수치)
        blank = True,                               # 빈 값 허용
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)

    # article = Article.objects.get(id=1)
    # user -> admin

    #1. 1:N
    # article.user # 게시글을 쓴 유저(admin)
    # user.article_set.all() # 유저(admin)가 쓴 게시글 전체 (겹침)

    #2. M:N
    # article.like_users # 1번 게시글을 좋아요 한 유저
    # user.article_set.all() # 유저가 좋아요 한 게시글 전체 (겹침)
    # --> user.like_articles.all() # 유저(admin)이 좋아요를 누른 모든 게시글들

    def __str__(self):
        return f'{self.id}: {self.title}'

class Comment(models.Model):
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)    # 1 대 N 의 관계
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

Web/04_django/LECTURE_CODE/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name',)

class UserCustomCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

Web/04_django/LECTURE_CODE/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from .forms import UserCustomChangeForm, UserCustomCreationForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

User = get_user_model()

def index(request):
    users = User.objects.all()
    context = {
        'users':users
    }
    return render(request, 'accounts/index.html', context)

def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == "POST":
        form = UserCustomCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = UserCustomCreationForm()
    return render(request, 'accounts/auth_form.html', {'form':form})

def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout(request):
    if request.method == "POST":
        auth_logout(request)
    return redirect('articles:index')

def delete(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    if request.method == "POST":
        user.delete()
    return redirect('articles:index')

def edit(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    if request.method == "POST":
        form = UserCustomChangeForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = UserCustomChangeForm(instance=user)
    return render(request, 'accounts/auth_form.html', {'form':form})

def change_password(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/auth_form.html', {'form':form})

@login_required
def profile(request, username):
    user = get_object_or_404(get_user_model(), username=username)    
    # if request.method == 'POST':
    return render(request, 'accounts/profile.html', {'user':user})
    # else:
    #     form = AuthenticationForm()
    # return render(request, 'accounts/login.html', {'form':form})

Web/04_django/LECTURE_CODE/accounts/templates/accounts/auth_form.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}

{% block body %}
{% if request.resolver_match.url_name == 'signup' %}
<h1 class="text-center">Sign Up</h1>
{% elif request.resolver_match.url_name == 'change_password' %}
<h1 class="text-center">Change Password</h1>
{% else %}
<h1 class="text-center">Edit Account</h1>
{% endif %}
<div class="container">
    <form action="" method="POST" style='display:inline'>
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% bootstrap_button "등록" button_type='submit' button_class='btn btn-dark' %}
    </form>
    <a href="{% url 'articles:index' %}" style='display:inline'><button class='btn btn-info'>목록보기</button></a>
</div>
{% endblock %}

Web/04_django/LECTURE_CODE/accounts/templates/accounts/index.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}
{% block body %}
  <div class="container">
    <h1>유저 목록</h1>
    <hr>
    {% for user in users %}
      <h3>{{ user.pk }}번 유저</h3>
      <h4>ID: {{ user.username }}</h4>
      <form action="{% url 'accounts:profile' user.username %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-warning">Profile</button>
      </form>
      <!-- <a href="{% url 'accounts:profile' user.username %}">Profile</a> -->
      <hr>
    {% endfor %}
  </div>  
{% endblock %}

Web/04_django/LECTURE_CODE/accounts/templates/accounts/login.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block title %}Log In{% endblock %}
{% block body %}
<h1 class="text-center">Log In</h1>
<div class='container'>
    <form action="" method="POST" style='display:inline'>
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% bootstrap_button "Log In" button_type='submit' button_class='btn btn-dark' %}
    </form>
    <a href="{% provider_login_url 'kakao' %}"><button class='btn btn-warning'>Kakao Log In</button></a>
    <a href="{% url 'articles:index' %}"><button class='btn btn-dark'>Cancel</button></a>
</div>
{% endblock %}

Web/04_django/LECTURE_CODE/accounts/templates/accounts/profile.html
{% extends 'boards/base.html' %}
{% block body %}
<div class="container">
  <div class="jumbotron text-center text-white bg-dark">
      <h1 class="text-center">{{ user.username }}'s Profile</h1>
      {% if user.email %}
        <h3>e-mail: {{ user.email }}</h3>
      {% else %}
        <h3>e-mail: no-info</h3>
      {% endif %}
      <p>Administrator: {{ user.is_superuser }}</p>
      <p class="lead">
          팔로잉 : {{ user.followings.all | length }}
          팔로워 : {{ user.followers.all | length }}
      </p>
  </div>
<hr>
<h3 class="text-center">{{ user.username }}이 작성한 글</h3>
<div class="row">
  {% for article in user.article_set.all %}
  <div class="col-4 my-2">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">No.{{ article.id }}: {{ article.title }}</h4>
        <p class="card-text">{{ article.like_users.count }}명이 좋아하는 글</p>
        <p class="card-text">{{ article.comment_set.count }}개의 댓글</p>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">게시글 보기</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<hr>

<h3 class="text-center">{{ user.username }}이 작성한 댓글</h3>
<div class="row">
  {% for comment in user.comment_set.all %}
  <div class="col-12 my-2">
    <div class="card">
      <div class="card-body">
        <blockquote class="blockquote">
          <p class="mb-0">{{ comment.content }}</p>
          <footer class="blockquote-footer">{{ comment.created_at|date:"SHORT_DATE_FORMAT" }}</footer>
        </blockquote>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<a href="{% url 'accounts:index' %}"><button class='btn btn-dark'>유저목록</button></a>
{% if user == request.user %}
<a href="{% url 'accounts:edit' user.pk %}"><button class='btn btn-dark'>회원정보 수정</button></a>
<a href="{% url 'accounts:change_password' user.pk %}"><button class='btn btn-dark'>비밀번호 변경</button></a>
<form action="{% url 'accounts:delete' user.pk %}" method="POST" style="display: inline">
  {% csrf_token %}
  <button class='btn btn-danger'>회원삭제</button>
</form>
{% endif %}
<a href="{% url 'articles:index' %}"><button class='btn btn-dark'>메인페이지</button></a>
</div>
{% endblock %}